// Deterministic GitHub writes — the model never touches git. Mirrors
// agent-runtime's recorder.ts: a path allowlist and our own code do the
// writing and pushing, never the agent. Uses the Contents API directly
// (no local clone needed for a handful of small JSON files) so the worker
// stays a plain Node script with zero dependencies.

const API = "https://api.github.com";

async function gh(token, path, opts = {}) {
  const res = await fetch(API + path, {
    ...opts,
    headers: {
      accept: "application/vnd.github+json",
      authorization: `Bearer ${token}`,
      "x-github-api-version": "2022-11-28",
      ...(opts.body ? { "content-type": "application/json" } : {}),
      ...opts.headers,
    },
  });
  if (!res.ok) {
    const body = await res.text();
    throw new Error(`GitHub API ${opts.method || "GET"} ${path} -> ${res.status}: ${body}`);
  }
  return res.status === 204 ? null : res.json();
}

function b64(str) {
  return Buffer.from(str, "utf8").toString("base64");
}

export async function findOpenBatchPr({ token, repo, dateStr }) {
  const branch = `content-batch-${dateStr}`;
  const prs = await gh(token, `/repos/${repo}/pulls?state=open&head=${repo.split("/")[0]}:${branch}`);
  return prs.length ? prs[0] : null;
}

export async function openContentBatchPr({ token, repo, baseBranch, dateStr, pages, images, backlogUpdate, summaryLines }) {
  const branchName = `content-batch-${dateStr}-${Date.now()}`;

  const baseRef = await gh(token, `/repos/${repo}/git/ref/heads/${baseBranch}`);
  const baseSha = baseRef.object.sha;

  await gh(token, `/repos/${repo}/git/refs`, {
    method: "POST",
    body: JSON.stringify({ ref: `refs/heads/${branchName}`, sha: baseSha }),
  });

  for (const page of pages) {
    const filePath = `content/pages/${page.slug}.json`;
    await gh(token, `/repos/${repo}/contents/${filePath}`, {
      method: "PUT",
      body: JSON.stringify({
        message: `Draft: ${page.title}`,
        content: b64(JSON.stringify(page, null, 2) + "\n"),
        branch: branchName,
      }),
    });
  }

  // SOP-AGENTIC-SEO-WEBSITES.md §8.5: the image lands in the SAME PR as its
  // page, opened by this same call -- no separate image-approval flow.
  // Contents API PUT wants base64 for binary files too, same endpoint as
  // the JSON writes above, just raw bytes instead of a UTF-8 string.
  for (const image of images || []) {
    const filePath = `assets/img/${image.filename}`;
    await gh(token, `/repos/${repo}/contents/${filePath}`, {
      method: "PUT",
      body: JSON.stringify({
        message: `Image: ${image.filename}`,
        content: image.buffer.toString("base64"),
        branch: branchName,
      }),
    });
  }

  if (backlogUpdate) {
    const existing = await gh(token, `/repos/${repo}/contents/content/backlog.json?ref=${branchName}`);
    await gh(token, `/repos/${repo}/contents/content/backlog.json`, {
      method: "PUT",
      body: JSON.stringify({
        message: "Mark batch items as drafted",
        content: b64(JSON.stringify(backlogUpdate, null, 2) + "\n"),
        branch: branchName,
        sha: existing.sha,
      }),
    });
  }

  const pr = await gh(token, `/repos/${repo}/pulls`, {
    method: "POST",
    body: JSON.stringify({
      title: `Content batch ${dateStr}: ${pages.length} page(s) awaiting review`,
      head: branchName,
      base: baseBranch,
      body: [
        "**Awaiting Jake's review — nothing here is live until this merges.**",
        "",
        "Generated by the agentic drafting worker (SOP-AGENTIC-SEO-WEBSITES.md). Each page passed the",
        "structural evidence gate (no unconfirmed claims, no unsafe HTML) before this PR was opened.",
        "",
        "Run `npm run build` locally or check the Netlify deploy preview to see the rendered pages.",
        "",
        "### Pages in this batch",
        ...summaryLines,
      ].join("\n"),
    }),
  });

  return { branchName, prUrl: pr.html_url, prNumber: pr.number };
}
